os: linux
dist: bionic

language:
    - c
    
before_install:
    - pip install --user cpp-coveralls
    
addons:
    sonarcloud:
        organization: "rakabidasta"
    token: $SONAR_TOKEN
    
script:
    - qmake 
    - make
    - ./tests/tests
    
after_success:
    - coveralls --root . -E ".*external.*" -E ".*tests.*" -E ".*main.c.*"
    - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
    - sonar-scanner
    
cache:
    directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
notifications:
    email: false
